### ISSUE TITLE
this._renderer._updateImg is not a function

### ISSUE THREAD

**Issue by alexLuky** [lipatoff/leaflet-canvas-markers#1]
I get this error:
> this._renderer._updateImg is not a function

when set regular png image.

here is my code:

```
let map = L.map("map", {
  center: [0, 0],
  zoom: 5
});

new L.tileLayer("http://tiles.maps.sputnik.ru/{z}/{x}/{y}.png").addTo(map);

let marker = L.canvasMarker(L.latLng(0, 0), {
  radius: 20,
  img: {
    url: 'icon.png',
    // url: "https://cdn2.iconfinder.com/data/icons/wsd-map-markers-1/512/wsd_markers_45-512.png", //image link
    size: [40, 40], //image size ( default [40, 40] )
    rotate: 0, //image base rotate ( default 0 )
    offset: { x: 0, y: 0 } //image offset ( default { x: 0, y: 0 } )
  }
}).addTo(map);
```

and here is sandbox online project playground:
https://codesandbox.io/s/prod-moon-xvnj8

I can't run this plugin even on my local html-directory.
Do you have any idea what can be wrong?

**Comment by lipatoff** [comment]
Hello! Install https://www.npmjs.com/package/leaflet-canvas-markers
And just add 
`import 'leaflet-canvas-markers';`

**Comment by alexLuky** [comment]
I've downloaded example directory and solved the issue. Thank you.
