### ISSUE TITLE
marker popup "bound" is not correct if offset option is used

### ISSUE THREAD

**Issue by easz** [lipatoff/leaflet-canvas-markers#10]
if I set offset other than {x: 0, y: 0} and have bindpopup on the marker, the "bounding box" of clickable area is not correct.

**Comment by lipton-ice-tea** [comment]
This option change only image offset in Canvas.

If you want change offset popup: `.bindPopup(coordinatesPopup, {offset: [10, 10]})`
If you want change offset marker: https://stackoverflow.com/a/29081069
