### ISSUE TITLE
Markers with svg icons do not show up on FireFox browser(81.0.2)

### ISSUE THREAD

**Issue by trbsi** [lipatoff/leaflet-canvas-markers#7]
Canvas markers with svg icons are not showing up on FF 81.0.2, while they are working on other browsers, chrome and IE.
Changed svg to png and it works fine.
However, svg is mandatory because png has got pixel issues when the icon is rotated

**Comment by lipton-ice-tea** [comment]
Fixed in https://github.com/lipton-ice-tea/leaflet-canvas-markers/releases/tag/1.0.7
