### ISSUE TITLE
How to find out if it is a instanceof L.canvasMarker?

### ISSUE THREAD

**Issue by henrikmaa** [lipatoff/leaflet-canvas-markers#8]
Is there a way to check if the layer is instanceof L.canvasMarker?

e.target instanceof L.canvsMarker // returns false
e.target instanecof L.circleMarker //also returns false

**Comment by lipton-ice-tea** [comment]
Use instanceof L.CircleMarker
```
const marker = L.canvasMarker(L.latLng(51.495, -0.06), {
   img: {
      url: '',
      size: [10, 10],
   },
}).addTo(map);
console.log(marker instanceof L.CircleMarker);
```
